---
jobs:

- name: job-unittest-service
  public: true
  plan:
  - get: fussball-demo-service
    trigger: true
  - task: unit-test-service
    file: fussball-demo-service/ci/unit-test-service.yml

- name: job-deploy-service
  public: true
  serial: true
  plan:
  - get: fussball-demo-service
    passed: [job-unittest-service]
    trigger: true
  - task: build-service
    file: fussball-demo-service/ci/build-service.yml
  - put: pws
    params:
      manifest: fussball-demo-service/fussball-service/manifest.yml

- name: job-smoketest-service
  public: true
  plan:
  - get: fussball-demo-service
    passed: [job-deploy-service]
    trigger: true
  - task: smoke-test-service
    file: fussball-demo-service/ci/smoke-test-service.yml

- name: job-deploy-www
  public: true
  serial: true
  plan:
  - get: fussball-demo-www
    trigger: true
  - task: build-www
    file: fussball-demo-www/ci/build-www.yml
    params:
      GOOGLE_MAPS_API_KEY: ((google-maps-api-key))
  - put: pws
    params:
      manifest: fussball-demo-www/www/manifest.yml

- name: job-prod-push
  public: true
  serial: true
  plan:
  - get: fussball-demo-service
    passed: [job-smoketest-service]
    trigger: false
  - task: prod-push
    file: fussball-demo-service/ci/prod-push.yml
    params:
      CF_API: https://api.run.pivotal.io
      CF_DOMAIN: cfapps.io
      CF_ORG: ((pws-org))
      CF_SPACE: ((pws-space))
      CF_USER: ((pws-username))
      CF_PASSWD: ((pws-password))

resources:

- name: fussball-demo-www
  type: git
  source:
    uri: https://github.com/pvtl-dnoguerol/fussball-demo.git
    branch: master
    paths: www

- name: fussball-demo-service
  type: git
  source:
    uri: https://github.com/pvtl-dnoguerol/fussball-demo.git
    branch: master
    paths: fussball-service

- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((pws-username))
    password: ((pws-password))
    organization: ((pws-org))
    space: ((pws-space))
    skip_cert_check: false
