---
platform: linux

image_resource:
  type: docker-image
  source: {repository: nulldriver/cf-cli-resource, tag: "2.6.0"}

inputs:
- name: fussball-demo

run:
  path: fussball-demo/ci/prod-push.sh
  user: root