---
platform: linux

image_resource:
  type: docker-image
  source: {repository: nulldriver/cf-cli-resource, tag: "2.6.0"}

inputs:
- name: fussball-demo-service

run:
  path: fussball-demo-service/ci/prod-service.sh
  user: root