---
platform: linux

image_resource:
  type: docker-image
  source: {repository: nulldriver/cf-cli-resource, tag: "2.6.0"}

inputs:
- name: fussball-demo-www

run:
  path: fussball-demo-www/ci/prod-www.sh
  user: root